export type NavItem = { label: string; href: string };
export type LinkItem = { label: string; href: string };
export type Action = { label: string; href: string; variant?: 'primary' | 'secondary' | 'outline' | 'ghost' };
export type TextItem = { title: string; body: string };
export type Step = { title: string; body: string };
export type Capability = { title: string; body: string; badge: string; signal: string; details: string[]; visual: string[]; featured?: boolean };
export type Benefit = { title: string; body: string };
export type ComparisonRow = { label: string; manageable: string; limitation: string; highlight?: boolean };
export type FaqItem = { question: string; answer: string };
